# Generated by Django 3.1.1 on 2020-11-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('ide', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.CharField(max_length=100)),
                ('fecha_modificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('ide', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.CharField(max_length=100)),
                ('fecha_modificacion', models.CharField(max_length=100)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.paises')),
            ],
        ),
        migrations.CreateModel(
            name='Afiliados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.CharField(max_length=100)),
                ('fecha_modificacion', models.CharField(max_length=100)),
                ('ide_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.ciudades')),
            ],
        ),
    ]
