# Generated by Django 3.1.1 on 2020-11-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10)),
                ('ide_tipo', models.CharField(max_length=10)),
                ('ide_raza', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('tiene_vacunas', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.CharField(max_length=100)),
                ('fecha_modificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Razas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=100)),
                ('id_tipo', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.CharField(max_length=100)),
                ('fecha_modificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_creacion', models.CharField(max_length=100)),
                ('fecha_modificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Afiliados',
        ),
    ]
